version: '3.5'

services:
  marketing:
    container_name: 'marketing'
    image: node:16
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL="postgresql://postgres:postgresd@localhost:5432/marketing?schema=public"
    volumes:
      - ./dist/:/app/dist/
      - ./package.json:/app/package.json
    command: bash -c "npm install --omit=dev --force && npm run start"
    depends_on:
      - postgres
  postgres:
    container_name: 'postgres'
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local
